spring.application.name=rest_api_request_body_validation


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Admin

#It shows SQL query.
spring.jpa.show-sql=true

#setting custome port no.
server.port=7799

#setting own custome custome path
server.servlet.context-path=/user



#spring.jpa.hibernate.ddl-auto=create